# DO NOT USE DIRECTLY
# Use environment specific (env/*) deployment configurations
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kustomize
resources:
- deployment.yaml
- service.yaml
- ingress.yaml